name: BlueGreenECSDeploy

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: webapp-cluster
  ECS_SERVICE: webapp-service
  APP_NAME: WebAppECSApp
  DEPLOYMENT_GROUP: WebAppDeploymentGroup
  S3_BUCKET: mehdyy-codedeploy-bucket
  IMAGE_URI: mehdyyy/webapp:latest

jobs:
  deploy:
    name: Deploy to ECS (Blue/Green)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::837369895208:role/GitHubActionsDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Update image in taskdef.json
        run: |
          sed -i "s|mehdyyy/webapp:latest|${{ env.IMAGE_URI }}|g" taskdef.json

      - name: Register new task definition
        id: task
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://taskdef.json | jq -r '.taskDefinition.taskDefinitionArn')
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Update appspec.yml
        run: sed -i "s|REPLACEME|$TASK_DEF_ARN|g" appspec.yml

      - name: Upload appspec to S3
        run: aws s3 cp appspec.yml s3://${{ env.S3_BUCKET }}/appspec.yml

      - name: Create deployment
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.APP_NAME }} \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ env.S3_BUCKET }},key=appspec.yml,bundleType=YAML \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
            --file-exists-behavior OVERWRITE
